
spring:
  ai:
    mcp:
      server:
        enabled: true
        name: mybuz-mcp-server
        version: "1.0.0"
        type: SYNC
        base-url:
        stdio: false
        prompt-change-notification: true
        resource-change-notification: true
        tool-change-notification: true
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message
        capabilities:
          completion: true
          prompt: true
          resource: true
          tool: true
        request-timeout: 20s

#        instructions:

server:
  port: 9090


